framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed
        default_bus: command.bus

        buses:
            command.bus: ~
            event.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    service: null
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
#            'App\Message\PurchaseConfirmationNotification': async
            'App\Message\Command\SaveOrder': sync
            'App\Message\Event\OrderSavedEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
